language: 
  - php

env:
  - LARAVEL_VERSION=5.0.*

matrix:
  include:
    - php: 7.1
      env: LARAVEL_VERSION=5.2.*
    - php: 7.1
      env: LARAVEL_VERSION=5.3.*
    - php: 7.1
      env: LARAVEL_VERSION=5.4.*
    - php: 7.1
      env: LARAVEL_VERSION=5.5.*

    - php: 7.2
      env: LARAVEL_VERSION=5.2.*
    - php: 7.2
      env: LARAVEL_VERSION=5.3.*
    - php: 7.2
      env: LARAVEL_VERSION=5.4.*
    - php: 7.2
      env: LARAVEL_VERSION=5.5.*
    - php: 7.2
      env: LARAVEL_VERSION=5.6.*
    - php: 7.2
      env: LARAVEL_VERSION=5.7.*
    - php: 7.2
      env: LARAVEL_VERSION=5.8.*
    - php: 7.2
      env: LARAVEL_VERSION=6.*

    - php: 7.3
      env: LARAVEL_VERSION=5.2.*
    - php: 7.3
      env: LARAVEL_VERSION=5.3.*
    - php: 7.3
      env: LARAVEL_VERSION=5.4.*
    - php: 7.3
      env: LARAVEL_VERSION=5.5.*
    - php: 7.3
      env: LARAVEL_VERSION=5.6.*
    - php: 7.3
      env: LARAVEL_VERSION=5.7.*
    - php: 7.3
      env: LARAVEL_VERSION=5.8.*

before_install:
  - travis_retry composer self-update
  - travis_retry composer require "laravel/framework:${LARAVEL_VERSION}" --no-interaction --no-update

install: 
  - travis_retry composer update --prefer-source --no-interaction

before_script:

script: 
  - vendor/bin/phpunit
